project_id_env: N-D-B_CROWDIN_PROJECT_ID
api_token_env: N-D-B_CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: "https://api.crowdin.com/"
commit_message: "chore: New translations %original_file_name% from Crowdin"
append_commit_message: false
preserve_hierarchy: true
files:
  - source: /en-US/*.json
    translation: /%locale%/%original_file_name%
