project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com/'
commit_message: 'chore: New translations %original_file_name% from Crowdin'
append_commit_message: 
preserve_hierarchy: 1
files:
  - source: /en-US/**/*.json
    translation: /%locale%/**/%original_file_name%
    update_option: update_as_unapproved
